### PR TITLE
Add support for ARM64v8 architecture

### PR DESCRIPTION
**Pull request by odidev**
This **PR** has been generated based on the ongoing discussion at https://github.com/aerospike/aerospike-server.docker/issues/33 .

Along with the mentioned changes i have also modified submodules being used in ```aerospike```.
These are:
**Use LuaJIT-2.1.0-beta3**
```    
      - git clone  http://luajit.org/git/luajit-2.0.git
      - git checkout v2.1.0-beta3
```
Please have a look and let know your valuable feedback.
I am open to do any kind of experimental changes if required to confirm and enhance ```aerospike``` for ```arm64v8``` architecture.

Regards,

### CODE REVIEW

**Comment by odidev** [comment]
This PR is raised in accordance with the ongoing discussion at https://github.com/aerospike/aerospike-server.docker/issues/33.

Please have a look at **Commit ID: 897920b**
Aerospike is working pretty well over arm64v8 after these changes an I can provide build and run logs as well.

I am also ready to perofrm test cases if required for further confirmation.
Regards,

**Comment by odidev** [comment]
In case you feel unavailability of platform for confirmation then please refer to this:
```
Shippable supports free Arm64 CI/CD and I believe Codefresh does too (both 64-bit and 32-bit for both providers):

https://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture
http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/

CodeFresh Beta signup: https://goo.gl/forms/aDhlk56jZcblYokj1

If you need raw infrastructure the WorksOnArm project will supply full servers if you want to deal with metal: https://github.com/worksonarm/cluster/
```

Do have a look and let me know if anything else is required to see ```Aerospike``` over ```arm64v8```.
Regards,

**Comment by bbulkow** [comment]
Hey Oidev,
Thanks for your work and contribution - I'm following up internally, sorry for the delay.

Have you filed a contributor licence agreement ( CLA ) which is standard and very similar to Google's CLA and the Apache CLA? https://www.aerospike.com/community/contributor/

If so, can you respond here with the rough date of your CLA submission?

We can't accept code changes without a valid CLA for your account - thanks.

**Comment by odidev** [comment]
@bbulkow 
Hi Brian,
It's great that you finally decided to have a look at the changes.
I have submitted CLA around August 23, 2018.

Do let me know, if there is somthing else required from my end.

Thanks for your cooperation :smile: :ok_hand: 
Regards,

**Comment by bbulkow** [comment]
Thanks, that helps me track things down.

**Comment by odidev** [comment]
@bbulkow 
Hi Brian,

Is there any update regarding the work in the direction of support for ```arm64v8```?
Eagerly waiting to see ```Aerospike``` in the official support list of ```arm64v8```.

Regards

**Comment by odidev** [comment]
Hi Guys,
Sorry to bother you again.

Is there any update w.r.t. ARM64?
Regards,

**Comment by brihh** [comment]
Greetings. Have you been able to run multi-node cluster tests on ARM?

thx.bri.

**Comment by lag-linaro** [comment]
@odidev I'm trying to replicate your build.

After pulling this Pull Request I ran:

```
$ git submodule init
$ git submodule update
$ make all
```
But I get:
```
make: *** No rule to make target '/src/luaconf.h.orig', needed by '/src/luaconf.h'. Stop.
```
Which  comes from this part of the `Makefile`:
```
$(LUAJIT)/src/luaconf.h: $(LUAJIT)/src/luaconf.h.orig
        ln -s $(notdir $<) $@
```
How did you fix this?

**Comment by odidev** [comment]
Hi @lag-linaro 
It is really great to see you getting involved in this module.
Sincere Thanks for this :smile: 

I am still stuck in trying to get multi-nodes working.

Please use below changes to get going:
```
Create symlink of src/luaconf.h -> src/luaconf.h.orig
```

You will also require LuaJIT for ARM64, for this, use this:
```
##### replace luaJIT ####
git clone http://luajit.org/git/luajit-2.0.git
git checkout v2.1.0-beta3
```
```
#### add this to modules/luajit-2.0/src/lauxlib.h
#define luaL_reg	luaL_Reg
```

Please let me know when it works for you

Regards,

**Comment by odidev** [comment]
Hi @lag-linaro 

Did you get success in compiling the Aerospike with informed changes?

Regards,

**Comment by lag-linaro** [comment]
Did you make any changes to the vanilla `v2.1.0-beta3` branch?

I get:

```
make -C /home/ubuntu/projects/docker-hub/aerospike-server/modules/luajit-2.0 Q= TARGET_SONAME=libluajit.so CCDEBUG=-g
make[1]: Entering directory '/home/ubuntu/projects/docker-hub/aerospike-server/modules/luajit-2.0'
==== Building LuaJIT 2.0.5 ====
make -C src
make[2]: Entering directory '/home/ubuntu/projects/docker-hub/aerospike-server/modules/luajit-2.0/src'
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^~~~~
lj_arch.h:294:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^~~~~
<snip>
```

**Comment by odidev** [comment]
Apart from above, you will require changes in following submodules too:
- mod-lua
```
--- a/Makefile
+++ b/Makefile
@@ -42,7 +42,7 @@ ifeq ($(USE_LUAJIT),1)
   CC_FLAGS += -DUSE_LUAJIT
 endif
 
-ifneq ($(ARCH),$(filter $(ARCH),ppc64 ppc64le))
+ifneq ($(ARCH),$(filter $(ARCH),ppc64 ppc64le, aarch64))
 CC_FLAGS += -march=nocona
 endif
```
- common
```
--- a/Makefile
+++ b/Makefile
@@ -15,7 +15,7 @@ CC_FLAGS += -fno-common -fno-strict-aliasing
 CC_FLAGS += -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE $(EXT_CFLAGS)
 
 ifneq ($(ARCH),$(filter $(ARCH),ppc64 ppc64le))
-CC_FLAGS += -march=nocona
+#CC_FLAGS += -march=nocona
 endif
 
```

- luajit-2.0
```
--- a/src/lauxlib.h
+++ b/src/lauxlib.h
@@ -158,4 +158,5 @@ LUALIB_API void (luaL_pushresult) (luaL_Buffer *B);
 
 /* }====================================================== */
 
+#define luaL_reg	luaL_Reg
 #endif
```

All the above changes can't be upstreamed as they are not part of ```Aerospike``` module

Regards,

**Comment by skynet4ps** [comment]
Sorry to bother you guys, but it has been a long time.
Is there any update w.r.t. work in direction of ARM64v8?

**Comment by kportertx** [comment]
@akhilgupta74 

Supporting architectures other than x86-64 is not a current priority. As Aerospike does make use of memory ordering guarantees provided by the x86-64 architecture, officially supporting architectures with weaker guarantees would require a significant financial and time investment, increase code complexity, and potentially reduce performance on x86-64.

If supporting ARM64v8 is a blocker for your company, I suggest negotiating with our [sales team](https://www.aerospike.com/forms/contact-us/).

**Comment by Halfi** [comment]
@kportertx in case of apple m1 released your last message looks offensively.

**Comment by kportertx** [comment]
@Halfi, I'm not sure what you find offensive, please clarify.

**Comment by Halfi** [comment]
@kportertx first of all , all of your competitors support arm64 (actually multi-arch builds). Now arm64 architecture become much more popular after apple m1 released. And I can't find more information about your position about arm64 architecture. Only low priority for this task and your comment.
I got that you use specific x86 instructions, but @obidev made it works with quit small pull request.

**Comment by kportertx** [comment]
The difficulty isn't the use of x86 specific instructions, those are relatively trivial to fix, the difficulty comes from the difference in memory ordering guarantees. This PR isn't complete (it doesn't address the memory ordering issues) and would require a significant investment to approach completion. Developments like AWS Graviton2 and Apple's M1 have significantly increased pressure to support ARM and support is on our roadmap.

**Comment by roman1v** [comment]
@odidev Sorry to bother you about this old topic...

Do you probably have the built docker image for arm64 you could share?

**Comment by kportertx** [comment]
6.2 has been released with ARM support: https://download.aerospike.com/download/server/notes.html#6.2.0.0

**Pull request closed without merging**
