### PR TITLE
build: add the possibility to use system provided jemalloc and jansson

### PR DESCRIPTION
**Pull request by ultrabug**
As per issue #57 I'm opening sub issues to focus on addressing some important points.

> The sources make extensive use of bundled libraries and do not provide any flag to use system-wide libs instead

I successfully managed to make use of system provided jemalloc and jansson libs to build a working asd thanks to this proposed PR. As you can see, I made it so it does not change any default behaviour in the current build system.

### CODE REVIEW

**Comment by psi-mankoski** [comment]
Thank you for the pull request.
A big difficulty with using a system-provided library is that it may not conform to the same API version (and behavior) as the submodule provided with the server source. Currently there is no means in the Aerospike server build to guarantee API version compliance for system-provided libraries, hence the use of fixed submodules. Can you propose such a means (short of going full-autoconf, which is not currently planned)?
In particular, the current development branch for next release (4.0.0?) of JEMalloc has incompatible API changes from the 3.6.0 version in the submodule. While these changes are relatively minor, it would not work "out of the box." (Unless/until conditionalizations or other changes were added.)
And while it appears that versions up to and including the latest version of Jansson (2.7.0) is API backward-compatible with the version in the submodule (v2.4-81-g5cc594c), it is still possible that the system-provided library behavior would differ from the included version we have certified against in our QA process.
Comments? Thanks!

**Comment by ultrabug** [comment]
> A big difficulty with using a system-provided library is that it may not conform to the same API version (and behavior) as the submodule provided with the server source

Then please set a clear version requirement for each system dependency. It's our packager role to conform to it and every package manager of Linux distributions handles dependencies so it does not seem a problem per se.

> Currently there is no means in the Aerospike server build to guarantee API version compliance for system-provided libraries, hence the use of fixed submodules. Can you propose such a means (short of going full-autoconf, which is not currently planned)?

This is already done in the packages themselves tho I understand your need to enforce it on the build system. I'm no autotools expert so I'm very unlikely to propose such a major change to the whole aerospike-server build system let alone the fact that I would do it without a real partner on your side which means that I will surely end up wasting hours of work for a refused PR.

> Comments? Thanks!

I'd like to point out that the proposed PR does NOT change the current build system. I made it so in order to not brake your QA process so I'm not sure I understand the main blocking point tbh ?

I understand that Aerospike is somewhat new to the Open Source world which explains your PoV. TBH I've had the same debates with the MongoDB guys a few years ago and they improved their build system to support using system-wide libs since then. I'm confident we'll find a way to make it happen with you guys :)

Cheers

**Comment by bbulkow** [comment]
I haven't reviewed the technical merits of this change, but our POV is not based on being "new to open source". Every member of the company has a long development experience, including stints in and out of open source. I was a Gentoo fanboy around 2006, although I never contributed, I liked the source distribution philosophy at that time.

Our POV is based around creating software with extraordinary uptime, with fully repeatable builds. Aerospike servers often have multi-year uptime. I personally worked on Netware 3.12, whose uptime is highlighted in the following Ars article (although I can't tell from the screenshot if that server was running my code --- most were)
http://arstechnica.com/information-technology/2013/03/epic-uptime-achievement-can-you-beat-16-years/

The way open source achieves high uptime is by multiple reviewers, open bug tracking, and individual projects switching libraries when they find one more to their taste. We switched from Clib to JEMalloc based on our testing and examination of the code. We have a specific patch level - essentially - of JEMalloc that we have reviewed and approve - a patch level that may or may not exist in your distribution. We believe we can do a better job of managing this key library relationship ( memory allocation being key for an in-memory database ! ) than package maintainers, and this is in the spirit of open source.

I agree with the philosophy of allowing people doing their own compile (and thus package maintainers)  to use libraries that are compatible as an option, but not as a default.

A build system that enables using system libraries, with properly specified version ranges, is a fine thing. I believe Psi asked how we allow and specify compatible versions without making shared library a default.

**Comment by ultrabug** [comment]
Thanks for your answer Brian

> I was a Gentoo fanboy around 2006, although I never contributed, I liked the source distribution philosophy at that time.

I remember talking to you about this yeah ;)

> We have a specific patch level - essentially - of JEMalloc that we have reviewed and approve - a patch level that may or may not exist in your distribution. We believe we can do a better job of managing this key library relationship ( memory allocation being key for an in-memory database ! ) than package maintainers, and this is in the spirit of open source.

That I can surely understand, even more especially on your Entreprise build and I fully trust your experience in this matter is by far more potent than any simple packager like us out there. The point is not about trusting or respect of your skills which I for one do a lot, it's only about having the choice.

> I agree with the philosophy of allowing people doing their own compile (and thus package maintainers) to use libraries that are compatible as an option, but not as a default.

And you can see that's exactly the point of this PR !

> A build system that enables using system libraries, with properly specified version ranges, is a fine thing. I believe Psi asked how we allow and specify compatible versions without making shared library a default.

Once again, I'm just a packager with very limited skills on this field and I absolutely trust your POV and Psi's advice on how this could happen. I never asked for this to be a default, I only point out that it's important imho to provide a clean way to have the choice which in the end you seem to agree on.

Thanks for your time mates ;)

**Comment by bbulkow** [comment]
Great, I expect Psi to respond in reasonable time... we're just a little cautious is all.

**Comment by bbulkow** [comment]
Hi - sorry for the delay here. We do want to support the use, but we'd like to engage - your pull request hit a conflict with some work we were doing. Expect a private email shortly.

**Comment by ultrabug** [comment]
Indeed @bbulkow quite a lot changed since then, this PR is obsolete. We'll follow-up by email, cheers.

**Pull request closed without merging**
