### PR TITLE
More informative warning message when maximum amount of stages was reached

### LINKED ISSUE #98: Add proper logging message if cannot allocate more stages
Here:
https://github.com/aerospike/aerospike-server/blob/9a80dee49517ef8a24d6b3b72b746a48bab08f33/cf/src/arenax_cold.c#L38

### PR DESCRIPTION
**Pull request by alexandrnikitin**
Fixes #98

### CODE REVIEW

**Comment by alexandrnikitin** [comment]
Hello?

**Comment by ariane6** [comment]
Appending your notifications on Twitter here: 
" One more unpleasant surprise from #aerospike 256GB memory size limit per node without documentation or error msg :(( "
"And I still don't see the RAM limitations in docs!"


The arenas we have set up are for internal bookkeeping; they don't constitute an external limitation. 

Thus, you are assuming there is a RAM limitation per node, but there is not; and there are no documentation changes to make on our part. 

If you've encountered an error when you've allocated more than 256GB of memory size, please send us the error message so we can work on your issue.

**Comment by alexandrnikitin** [comment]
The discussion goes in wrong direction. Those quotes aren't related to this pull request. Don't you find that? Here I want to see a clear error message when aerospike cannot allocate more stages because it reached the limit (which is [256 at the moment][limit]. Coincidence?)

  [limit]: https://github.com/aerospike/aerospike-server/blob/9a80dee49517ef8a24d6b3b72b746a48bab08f33/cf/include/arenax.h#L48

**Comment by alexandrnikitin** [comment]
BTW, where are developers?

**Comment by wchu-citrusleaf** [comment]
Thanks for the PR. Yes, agreed message should be added. Can you submit a contributor's Agreement - http://www.aerospike.com/community/contributor/license.html

**Comment by alexandrnikitin** [comment]
I signed it with this PR 2 weeks ago. Tell me if I need to resubmit it please.

**Comment by ariane6** [comment]
Confirming that we have the Community Contributor License Agreement you submitted - thank you.

**Comment by wchu-citrusleaf** [comment]
pulled into internal repo. Will be pushed out w/ slight mod in next release or so.

**Comment by alexandrnikitin** [comment]
@wchu-citrusleaf I can close the PR but I don't see that message in current master https://github.com/aerospike/aerospike-server/blob/master/cf/src/arenax_cold.c.

**Comment by wchu-citrusleaf** [comment]
We haven't pushed it out again. Will definitely update once it goes out with the release. Thanks.

**Comment by alexandrnikitin** [comment]
I see my commit in master and happy to close this PR. Thanks!

**Pull request closed without merging**
